import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import ToasterProvider from "./ToasterProvider";
import { Providers } from "./Providers";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
    title: "Reppoo",
    description: "Generated by create next app",
    icons: {
        icon: "/logo.svg",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${manrope.variable} cursor-default antialiased`}>
                <Providers>
                    <ToasterProvider />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
